### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by acrazing** [acrazing/kcats#3]
- [ ] core
	- [x] store
		- [x] getPreloadedState (for persist)
		- [x] subscribe
		- [x] dispatch
			- [x] transaction
		- [x] snapshot
		- [x] select
			- [x] cache
	- [x] selector
		- [ ] generic
	- [x] action
		- [x] basic
		- [x] optimistic action
		- [x] conflict policy
		- [x] key(for conflict and useAction)
		- [ ] generic
	- [x] box
		- [ ] selector chain
- [x] shapes
	- [x] record
	- [x] map
	- [x] list
	- [x] set
- [x] boxes
	- [x] record box
	- [x] map box
	- [x] list box
	- [ ] set box
	- [x] record map box
	- [x] list map box
	- [ ] set map box
- [x] persist
	- [ ] expiration
	- [x] version
	- [ ] customize persisted state (for filter map box items)
- [x] devtools
- [x] react binding
	- [x] basic(Provider/useSelector/useDispatch/useStore)
	- [x] useAction: dispatch action directly without useEffect
	- [x] useSuspenseAction: dispatch action and work with react suspense
- [ ] io
	- [ ] http action
	- [ ] paged list
- [ ] offline
